homeassistant:
  # Name of the location where Home Assistant is running
  name: Domov
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Prague
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# SSL
http:
    api_password: !secret api_password
    ssl_certificate: /etc/letsencrypt/live/home.josefkuchar.com/fullchain.pem
    ssl_key: /etc/letsencrypt/live/home.josefkuchar.com/privkey.pem
    base_url: home.josefkuchar.com

# Sensors
sensor:
  # SSL Cert
  - platform: command_line
    name: ssl_cert
    friendly_name: SSL Certifikát
    unit_of_measurement: dní
    scan_interval: 10800
    command: "ssl-cert-check -b -c /etc/letsencrypt/live/home.josefkuchar.com/cert.pem | awk '{ print $NF }'"
  - platform: steam_online
    api_key: !secret steam_api
    accounts:
      - 76561198079981349 # Me  
  - platform: syncthru
    resource: http://192.168.0.99
    name: Printer


# Text to speech
tts:
  - platform: google
    language: 'cs'

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

wake_on_lan:

weather:
  - platform: darksky
    name: Počasí
    mode: daily
    api_key: !secret weather_api

media_player:
  - platform: webostv
    host: 192.168.0.171
    filename: webostv.conf
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: !secret tv_mac

notify:
  - platform: webostv
    host: 192.168.0.171
    name: tv
    filename: webostv.conf

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.0.0/24
    interval_seconds: 120
    consider_home: 300
    # sudo setcap cap_net_raw,cap_net_admin,cap_net_bind_service+eip /usr/bin/nmap
    scan_options: " --privileged -sP "
    exclude:
      - 192.168.0.1
  - platform: edimax_extender
    interval_seconds: 120
    host: '192.168.0.101'

config:
