title: Domov
views:
    # View tab title.
  - title: Obývací pokoj
    id: living_room
    # Makes the first card fill the view
    cards:
        # The markdown card will render markdown text.
      - type: media-control
        entity: media_player.lg_webos_smart_tv
      - type: glance
        columns: 2
        entities:
          - device_tracker.bedroom_pc
          - device_tracker.living_room_pc
          - device_tracker.xiaomi_redmi_note_3
          - device_tracker.xiaomi_mi_a1
          - device_tracker.samsung_galaxy_s4
          - device_tracker.school_notebook
      - type: sensor
        name: SSL Certifikát
        entity: sensor.ssl_cert
      - type: weather-forecast
        entity: weather.pocasi
      - type: glance
        title: Steam
        entities:
          - sensor.steam_76561198079981349
      - type: sensor
        name: Toner tiskárny
        entity: sensor.samsung_m2070_series_192168099_toner_black
      - type: light
        entity: light.bedroom_light
        name: Noční světlo
