substitutions:
    ip: 192.168.0.200

wifi: !include wifi.yaml

esphomeyaml: !include esphomeyaml.yaml

api:
    password: !secret general_password

ota:
    password: !secret general_password


output:
  - platform: esp8266_pwm
    pin: D8
    frequency: 1000 Hz
    id: pwm_output

light:
  - platform: monochromatic
    name: 'Bedroom light'
    output: pwm_output
    id: light

binary_sensor:
  - platform: gpio
    pin:
        number: D7
        mode: INPUT_PULLUP
        inverted: true
    name: 'Light button'
    on_click:
        then:
          - light.toggle: light

sensor:
  - platform: rotary_encoder
    name: 'Light encoder'
    pin_a:
        number: D5
        mode: INPUT_PULLUP
        inverted: true
    pin_b:
        number: D6
        mode: INPUT_PULLUP
        inverted: true